# Generated by Django 5.0.3 on 2024-03-21 18:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Characteristic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Год выхода", "Year of release"),
                            ("Процессор", "CPU"),
                            ("Графический ускоритель", "GPU"),
                            ("Диагональ экрана(в дюймах)", "Screen diagonal"),
                            ("Матрица", "Matrix"),
                            ("Частота обновления экрана", "Screen refresh rate"),
                            ("Объем оперативной памяти", "RAM"),
                            ("Объем встроенной памяти", "Memory capacity"),
                            ("Eмкость аккумулятора", "Battery capacity"),
                        ],
                        max_length=128,
                        verbose_name="Название",
                    ),
                ),
                ("value", models.CharField(max_length=128, verbose_name="Значение")),
            ],
            options={
                "verbose_name": "Характеристика",
                "verbose_name_plural": "Характеристики",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Название")),
                ("slug", models.SlugField(max_length=128, verbose_name="Слаг")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shop.category",
                        verbose_name="Родитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Название")),
                ("slug", models.SlugField(max_length=128, verbose_name="Слаг")),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("Черный", "Black"),
                            ("Белый", "White"),
                            ("Розовый", "Pink"),
                            ("Космический серый", "Space gray"),
                        ],
                        max_length=128,
                        verbose_name="Цвет",
                    ),
                ),
                ("price", models.PositiveIntegerField(verbose_name="Цена")),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=0,
                        default=Decimal("0"),
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "discount_price",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Цена по скидке"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="shop.category",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "characteristics",
                    models.ManyToManyField(
                        related_name="exercises",
                        to="shop.characteristic",
                        verbose_name="Характеристики",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
    ]
