# Generated by Django 5.0.3 on 2024-03-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_usercart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercart",
            name="quantity",
            field=models.PositiveIntegerField(default=0, verbose_name="Количество"),
        ),
    ]
