# Generated by Django 5.0.3 on 2024-03-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_alter_usercart_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercart",
            name="sum",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
